version: '3.8'
services:
  api:
    image: nestjs-film-api
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres

    environment:
      NODE_ENV: development
      PORT: 3000

    ports:
      - '8080:3000'

  postgres:
    image: postgres:13
    ports:
      - '35000:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: ${TYPEORM_DB_PASSWORD}
